---
# tasks file for ansible-skeleton


- hosts: web
  become_user: ansible-admin
  become: true
  gather_facts: false
  
  tasks:
    - name: "Print on remote hosts"
      command: 'echo "testing remote"'
      register: output
      debug:
        msg: {{ output.stdout }}

    - name: "Print on localhost"
      command: 'echo "testing local"'
      register: output_local
      debug:
        msg: {{ output_local }}
      delegate_to: localhost
