---
# tasks file for ansible-skeleton


- nodes: all
  become_user: root
  gather_facts: yes
  
  tasks:
    - name: "Print on remote hosts"
      module_name: this

    - name: "Print on localhost"
      module: that

    - name: "Make JSON based REST API call"
      ????
