---
# tasks file for ansible-skeleton


- hosts: all
  gather_facts: false
  
  tasks:
    - name: "Print on remote hosts"
      print:
        msg: "testing remote"
      
    - name: "Print on localhost"
      print:
        msg: "testing local"
